"""Encabezados en español para los CSV (`app.core.csv`).

El dueño abre las descargas en Excel en español: un encabezado `business_date`
o `unit_cost` es una palabra de programador. Cada columna se nombra así, en
este orden:

1. el mapeo propio del endpoint (`csv_response(..., headers={...})`), para
   lo que en esa pantalla se llama distinto;
2. `KEYS`, el glosario de claves completas que se repiten en todo el sistema;
3. `TOKENS`, palabra por palabra, con el orden del español (el núcleo
   adelante: `unit_price` → «Precio unitario»).

`tests/core/test_csv.py` recorre TODOS los esquemas de respuesta de la API y
falla si alguna palabra de un campo no tiene traducción: un campo nuevo con una
palabra nueva no puede llegar a un CSV en inglés sin que un test lo diga.
"""

from __future__ import annotations

import re

#: Claves completas: ganan sobre la traducción palabra por palabra.
KEYS: dict[str, str] = {
    "no_show_count": "No vinieron",
    "id": "ID",
    "store_id": "ID sede",
    "organization_id": "ID organización",
    "name": "Nombre",
    "status": "Estado",
    "kind": "Tipo",
    "type": "Tipo",
    "notes": "Notas",
    "note": "Nota",
    "reason": "Motivo",
    "business_date": "Fecha operativa",
    "date": "Fecha",
    "from": "Desde",
    "to": "Hasta",
    "date_from": "Desde",
    "date_to": "Hasta",
    "created_at": "Creado (fecha y hora)",
    "updated_at": "Actualizado (fecha y hora)",
    "amount": "Monto",
    "total": "Total",
    "subtotal": "Subtotal",
    "qty": "Cantidad",
    "unit": "Unidad",
    "unit_price": "Precio unitario",
    "unit_cost": "Costo unitario",
    "total_cost": "Costo total",
    "cost": "Costo",
    "cost_source": "Origen del costo",
    "price": "Precio",
    "active": "Activo",
    "enabled": "Habilitado",
    "employee_id": "ID empleado",
    "employee_name": "Empleado",
    "ingredient_id": "ID insumo",
    "ingredient_name": "Insumo",
    "product_id": "ID producto",
    "product_name": "Producto",
    "category_id": "ID categoría",
    "category_name": "Categoría",
    "supplier_id": "ID proveedor",
    "supplier_name": "Proveedor",
    "shift_id": "ID turno",
    "order_id": "ID comanda",
    "platform_id": "ID plataforma",
    "platform_name": "Plataforma",
    "full_number": "Número completo",
    "doc_number": "Número de documento",
    "doc_type": "Tipo de documento",
    "gross": "Venta bruta",
    "net": "Venta neta",
    "tax": "Impuesto",
    "tax_total": "Total impuesto",
    "discount_total": "Total descuentos",
    "tip": "Propina",
    "tips": "Propinas",
    "orders": "Comandas",
    "count": "Cantidad",
    "sort_order": "Orden",
    "description": "Descripción",
    "label": "Rótulo",
    "turned_off_dependents": "Dependientes apagadas",
    "code": "Código",
    "value": "Valor",
    "year": "Año",
    "month": "Mes",
    "number": "Número",
    "seats": "Sillas",
    "zone_id": "ID zona",
    "zone_name": "Zona",
    "key": "Clave",
    "channel": "Canal",
    "method": "Medio",
    "payment_method": "Medio de pago",
    "reference": "Referencia",
    "valid_from": "Vigente desde",
    "valid_until": "Vigente hasta",
    "expires_at": "Vence",
    "is_critical": "Es crítico",
    "level": "Nivel",
    "title": "Título",
    "body": "Detalle",
    "read_at": "Leído (fecha y hora)",
    "prefix": "Prefijo",
    "consumed": "Consumidos",
    "resolution_number": "Número de resolución",
    "resolution_date": "Fecha de resolución",
    "technical_key": "Clave técnica",
    "document_type": "Tipo de documento",
    "dian_status": "Estado DIAN",
    "issued_at": "Expedido (fecha y hora)",
    "margin_pct": "Margen (%)",
    "food_cost_pct": "Food cost (%)",
    "variance_pct": "Varianza (%)",
    "stock": "Existencia",
    "min_stock": "Mínimo",
    "expected": "Esperado",
    "counted": "Contado",
    "difference": "Diferencia",
    "opened_at": "Abierto (fecha y hora)",
    "closed_at": "Cerrado (fecha y hora)",
    "role": "Rol",
    "puesto": "Puesto",
    "email": "Correo",
    "phone": "Teléfono",
    "address": "Dirección",
    "nit": "NIT",
    "dv": "DV",
    "uvt": "UVT",
    # Etiquetas de cocina (0036).
    "use_by": "Usar antes de",
    "use_by_source": "Origen de la fecha",
    "days_left": "Días que le quedan",
    "item_name": "Producto",
    "qty_text": "Contenido",
    "lot_code": "Lote",
    "print_count": "Veces impresa",
    "waste_unit": "Unidad de merma",
    "labels_printed": "Etiquetas impresas",
    "expired_names": "Lo vencido",
    "closed_by_employee_name": "Cerrada por",
    "use_by_preview": "Usar antes de (si se imprime ya)",
    "use_by_source_preview": "Origen de la fecha (si se imprime ya)",
}

#: Palabra por palabra. Cubre toda palabra de todo campo de todo esquema de
#: respuesta de la API (lo verifica `tests/core/test_csv.py`).
TOKENS: dict[str, str] = {
    # c5 · obligaciones recurrentes, abonos, agenda, INC y nómina agendada.
    "already": "ya",
    "bimester": "bimestre",
    "create": "por crear",
    "deactivated": "desactivada",
    "effective": "vigente",
    "existed": "existía",
    "horizon": "horizonte",
    "interval": "intervalo",
    "month": "mes",
    "months": "meses",
    "obligation": "obligación",
    "rates": "tarifas",
    "scheduled": "agendada",
    "template": "plantilla",
    "templates": "plantillas",
    "upcoming": "por vencer",
    # 0046 · libro del banco completo.
    "anchor": "extracto",
    "age": "antigüedad",
    "assignable": "movible de cuenta",
    "counter": "contraparte",
    "inflows": "entradas",
    "outflows": "salidas",
    "gmf": "4×1000",
    "exempt": "exenta",
    "mille": "mil",
    "receives": "recibe",
    "recurring": "recurrentes",
    "starting": "inicial",
    "allergens": "alérgenos",
    "absence": "novedad",
    "accountant": "contador",
    "admin": "administrador",
    "capability": "capacidad",
    "operator": "operador",
    "supervisor": "supervisor",
    "otpauth": "otpauth",
    "uri": "uri",
    "recovery": "recuperación",
    "secret": "secreto",
    "totp": "2fa",
    "allowance": "auxilio",
    "arl": "arl",
    "benefits": "prestaciones",
    "bonus": "prima",
    "contributions": "aportes",
    "employer": "empleador",
    "exonerated": "exonerado",
    "family": "familiar",
    "fund": "caja",
    "health": "salud",
    "icbf": "icbf",
    "interest": "intereses",
    "pension": "pensión",
    "ppm": "ppm",
    "provision": "provisión",
    "recoverable": "recobrable",
    "risk": "riesgo",
    "salary": "sueldo",
    "sena": "sena",
    "service": "servicios",
    "severance": "cesantías",
    "smmlv": "smmlv",
    "transport": "transporte",
    "vacation": "vacaciones",
    "114": "114",
    "1": "1",
    "par": "par",
    "band": "franja",
    "recount": "recuento",
    "lock": "bloqueo",
    "attempts": "intentos",
    "prep": "producción",
    "jump": "salto",
    "quick": "rápidas",
    "suggest": "sugerir",
    "warning": "aviso",
    "7": "7",
    "above": "encima",
    "abs": "absoluto",
    "accepted": "aceptado",
    "account": "cuenta",
    "accounts": "cuentas",
    "action": "acción",
    "active": "activo",
    "activity": "actividad",
    "actor": "actor",
    "address": "dirección",
    "adjustment": "ajuste",
    "after": "después",
    "aging": "antigüedad",
    "alert": "alerta",
    "alerts": "alertas",
    "allocated": "asignado",
    "allocations": "asignaciones",
    "amount": "monto",
    "answered": "respondido",
    "apart": "aparte",
    "applied": "aplicado",
    "approved": "aprobado",
    "area": "área",
    "areas": "áreas",
    "as": "como",
    "asked": "pedido",
    "at": "momento",
    "attendance": "asistencia",
    "auth": "autorización",
    "authorizations": "autorizaciones",
    "authorized": "autorizado",
    "authorizer": "autorizador",
    "available": "disponible",
    "average": "promedio",
    "avg": "promedio",
    "bad": "malo",
    "balance": "saldo",
    "balanced": "cuadrado",
    "bank": "banco",
    "banks": "bancos",
    "base": "base",
    "based": "basado",
    "basis": "base",
    "batch": "lote",
    "before": "antes",
    "behind": "atrasado",
    "below": "debajo",
    "best": "mejor",
    "beyond": "más allá",
    "bill": "cuenta",
    "body": "cuerpo",
    "bp": "(pb)",
    "break": "equilibrio",
    "breakdown": "desglose",
    "bucket": "franja",
    "bullet": "viñeta",
    "bullets": "viñetas",
    "bumped": "despachado",
    "business": "operativo",
    "by": "por",
    "calculation": "cálculo",
    "can": "puede",
    "cancel": "cancelación",
    "cancelled": "cancelado",
    "card": "tarjeta",
    "cards": "tarjetas",
    "carried": "arrastrado",
    "cash": "efectivo",
    "categories": "categorías",
    "category": "categoría",
    "cause": "causa",
    "change": "cambio",
    "changed": "cambiado",
    "channel": "canal",
    "channels": "canales",
    "charge": "cargo",
    "charged": "cobrado",
    "chart": "gráfica",
    "check": "verificación",
    "checks": "verificaciones",
    "class": "clase",
    "classification": "clasificación",
    "clear": "claro",
    "close": "cierre",
    "closed": "cerrado",
    "closes": "cierres",
    "closing": "cierre",
    "code": "código",
    "codes": "códigos",
    "collected": "recogido",
    "combo": "combo",
    "combos": "combos",
    "commission": "comisión",
    "comparison": "comparación",
    "comparisons": "comparaciones",
    "complete": "completo",
    "completed": "completado",
    "computed": "calculado",
    "configured": "configurado",
    "confirm": "confirmar",
    "confirmation": "confirmación",
    "confirmed": "confirmado",
    "consent": "consentimiento",
    "consumed": "consumido",
    "consumer": "consumidor",
    "consumption": "consumo",
    "contact": "contacto",
    "content": "contenido",
    "contingency": "contingencia",
    "contribution": "contribución",
    "cost": "costo",
    "costed": "costeado",
    "costs": "costos",
    "count": "conteo",
    "counted": "contado",
    "counts": "conteos",
    "courier": "domiciliario",
    "couriers": "domiciliarios",
    "course": "curso",
    "courses": "cursos",
    "courtesies": "cortesías",
    "courtesy": "cortesía",
    "cover": "cobertura",
    "covers": "comensales",
    "created": "creado",
    "critical": "crítico",
    "cude": "CUDE",
    "cumulative": "acumulado",
    "current": "actual",
    "customer": "cliente",
    "customers": "clientes",
    "cutoff": "corte",
    "daily": "diario",
    "dane": "DANE",
    "data": "datos",
    "date": "fecha",
    "day": "día",
    "days": "días",
    "declared": "declarado",
    "delivered": "entregado",
    "default": "por defecto",
    "delivery": "domicilio",
    "delta": "variación",
    "denominations": "denominaciones",
    "deposit": "consignación",
    "deposited": "consignado",
    "deposits": "consignaciones",
    "description": "descripción",
    "destination": "destino",
    "detail": "detalle",
    "device": "dispositivo",
    "dian": "DIAN",
    "diff": "diferencia",
    "difference": "diferencia",
    "dine": "mesa",
    "direction": "dirección",
    "discount": "descuento",
    "discounting": "descontando",
    "discounts": "descuentos",
    "discrepancy": "discrepancia",
    "dish": "plato",
    "distribution": "distribución",
    "doc": "documento",
    "document": "documento",
    "documents": "documentos",
    "dog": "perro",
    "done": "hecho",
    "drafts": "borradores",
    "drawer": "cajón",
    "drift": "desvío",
    "due": "vence",
    "dv": "DV",
    "effect": "efecto",
    "elapsed": "transcurrido",
    "electronic": "electrónico",
    "email": "correo",
    "employee": "empleado",
    "enabled": "habilitado",
    "end": "fin",
    "endpoint": "endpoint",
    "engineering": "ingeniería",
    "entered": "ingresado",
    "entity": "entidad",
    "entries": "asientos",
    "entry": "asiento",
    "envelope": "sobre",
    "envelopes": "sobres",
    "equation": "ecuación",
    "erased": "borrado",
    "error": "error",
    "estimated": "estimado",
    "evaluated": "evaluado",
    "even": "equilibrio",
    "exact": "exacto",
    "exceeds": "excede",
    "excluded": "excluido",
    "expected": "esperado",
    "expedited": "agilizado",
    "expenses": "gastos",
    "expired": "vencido",
    "expires": "vence",
    "expiring": "por vencer",
    "expiry": "vencimiento",
    "external": "externo",
    "factor": "factor",
    "failed": "fallido",
    "features": "funciones",
    "fee": "tarifa",
    "final": "final",
    "fired": "disparado",
    "fiscal": "fiscal",
    "fixed": "fijo",
    "flag": "marca",
    "flagged": "marcado",
    "flags": "marcas",
    "follow": "seguimiento",
    "food": "food",
    "franchise": "franquicia",
    "frequent": "frecuente",
    "from": "desde",
    "full": "completo",
    "fully": "completamente",
    "future": "futuro",
    "gap": "brecha",
    "generated": "generado",
    "given": "dado",
    "granted": "otorgado",
    "gross": "bruto",
    "group": "grupo",
    "groups": "grupos",
    "handovers": "entregas",
    "hash": "hash",
    "history": "historial",
    "holiday": "festivo",
    "hour": "hora",
    "hourly": "por hora",
    "hours": "horas",
    "id": "ID",
    "identified": "identificado",
    "ids": "IDs",
    "in": "en",
    "inc": "INC",
    "includes": "incluye",
    "incomes": "ingresos",
    "incoming": "entrante",
    "index": "índice",
    "inflow": "entrada",
    "ingredient": "insumo",
    "ingredients": "insumos",
    "insufficient": "insuficiente",
    "into": "hacia",
    "inventory": "inventario",
    "invoice": "factura",
    "invoiced": "facturado",
    "invoices": "facturas",
    "involved": "involucrado",
    "is": "es",
    "issued": "expedido",
    "item": "ítem",
    "items": "ítems",
    "iva": "IVA",
    "key": "clave",
    "keys": "claves",
    "kind": "tipo",
    "kitchen": "cocina",
    "kpi": "indicador",
    "label": "rótulo",
    "lag": "retraso",
    "last": "último",
    "late": "demorado",
    "latest": "más reciente",
    "lead": "entrega",
    "legal": "legal",
    "legend": "leyenda",
    "level": "nivel",
    "liability": "pasivo",
    "life": "vida",
    "light": "semáforo",
    "limit": "límite",
    "line": "línea",
    "lines": "líneas",
    "list": "lista",
    "loan": "préstamo",
    "loans": "préstamos",
    "long": "larga",
    "lookback": "ventana",
    "loss": "pérdida",
    "lost": "perdido",
    "lot": "lote",
    "lots": "lotes",
    "low": "baja",
    "manifest": "manifiesto",
    "margin": "margen",
    "marked": "marcado",
    "matched": "cruzado",
    "max": "máximo",
    "median": "mediana",
    "members": "miembros",
    "menu": "menú",
    "merged": "unido",
    "message": "mensaje",
    "method": "medio",
    "methods": "medios",
    "min": "mínimo",
    "mine": "mío",
    "minutes": "minutos",
    "seconds": "segundos",
    # Turnos planeados (auditoría e1).
    "minute": "minuto",
    "planned": "planeado",
    "actual": "real",
    "grace": "gracia",
    "copied": "copiados",
    "show": "presentación",
    "missing": "faltante",
    "mix": "mezcla",
    "mode": "modo",
    "modified": "modificado",
    "modifier": "modificador",
    "modifiers": "modificadores",
    "moment": "momento",
    "monthly": "mensual",
    "movement": "movimiento",
    "movements": "movimientos",
    "municipality": "municipio",
    "my": "mío",
    "n": "n",
    "name": "nombre",
    "needs": "requiere",
    "negative": "negativo",
    "net": "neto",
    "new": "nuevo",
    "next": "siguiente",
    "night": "noche",
    "nit": "NIT",
    "no": "sin",
    "not": "no",
    "note": "nota",
    "notes": "notas",
    "nothing": "nada",
    "notification": "aviso",
    "novelties": "novedades",
    "now": "ahora",
    "null": "nulo",
    "number": "número",
    "obligations": "obligaciones",
    "obliged": "obligado",
    "occupied": "ocupado",
    "of": "de",
    "official": "oficial",
    "oldest": "más antiguo",
    "on": "en",
    "open": "abierto",
    "opened": "abierto",
    "opening": "apertura",
    "operated": "operado",
    "option": "opción",
    "options": "opciones",
    "or": "o",
    "order": "comanda",
    "orders": "comandas",
    "ordinary": "ordinario",
    "organization": "organización",
    "other": "otro",
    "out": "salida",
    "outflow": "salida",
    "outside": "fuera",
    "outstanding": "pendiente",
    "over": "sobre",
    "overage": "sobrante",
    "overdue": "vencido",
    "overpaid": "pagado de más",
    "overtime": "horas extra",
    "p256dh": "p256dh",
    "pace": "ritmo",
    "paid": "pagado",
    "pareto": "Pareto",
    "part": "parte",
    "partial": "parcial",
    "parts": "partes",
    "password": "contraseña",
    "pause": "pausa",
    "pay": "pago",
    "payable": "cuenta por pagar",
    "payables": "cuentas por pagar",
    "payload": "contenido",
    "payment": "pago",
    "payments": "pagos",
    "payouts": "desembolsos",
    "payroll": "nómina",
    "pct": "(%)",
    "peak": "pico",
    "pending": "pendiente",
    "people": "personas",
    "per": "por",
    "period": "período",
    "perishable": "perecedero",
    "person": "persona",
    "pesos": "pesos",
    "petty": "menor",
    "phase": "fase",
    "phone": "teléfono",
    "photo": "foto",
    "pickup": "retiro",
    "pickups": "retiros",
    "pieces": "piezas",
    "pin": "PIN",
    "platform": "plataforma",
    "plowhorse": "caballo de batalla",
    "points": "puntos",
    "popularity": "popularidad",
    "portions": "porciones",
    "preparation": "preparación",
    "prefilled": "prellenado",
    "prefix": "prefijo",
    "preps": "preparaciones",
    "present": "presente",
    "presented": "presentado",
    "previous": "anterior",
    "price": "precio",
    "prices": "precios",
    "print": "impresión",
    "printed": "impreso",
    "probable": "probable",
    "process": "proceso",
    "produced": "producido",
    "product": "producto",
    "production": "producción",
    "products": "productos",
    "profile": "perfil",
    "profit": "utilidad",
    "progress": "avance",
    "promised": "prometido",
    "provider": "proveedor",
    "public": "público",
    "puesto": "puesto",
    "purchase": "compra",
    "purchases": "compras",
    "purpose": "finalidad",
    "puzzle": "enigma",
    "qr": "QR",
    "qty": "cantidad",
    "quantity": "cantidad",
    "range": "rango",
    "rate": "tasa",
    "ratio": "razón",
    "read": "leído",
    "reading": "lectura",
    "ready": "listo",
    "real": "real",
    "reason": "motivo",
    "reasons": "motivos",
    "receipt": "recibo",
    "receivable": "por cobrar",
    "received": "recibido",
    "recent": "reciente",
    "reception": "recepción",
    "receptions": "recepciones",
    "recommendation": "recomendación",
    "recommended": "recomendado",
    "recounted": "recontado",
    "recounts": "recuentos",
    "red": "rojo",
    "ref": "referencia",
    "reference": "referencia",
    "refund": "devolución",
    "refunds": "devoluciones",
    "regime": "régimen",
    "registered": "registrado",
    "rejected": "rechazado",
    "remaining": "restante",
    "removed": "quitado",
    "replaces": "reemplaza",
    "reprint": "reimpresión",
    "reprints": "reimpresiones",
    "request": "solicitud",
    "requested": "solicitado",
    "requests": "solicitudes",
    "required": "obligatorio",
    "requires": "requiere",
    "reserve": "base de respaldo",
    "resolution": "resolución",
    "resolved": "resuelto",
    "responded": "respondido",
    "response": "respuesta",
    "responsible": "responsable",
    "restocked": "reabastecido",
    "retention": "retención",
    "returned": "devuelto",
    "returns": "devoluciones",
    "revenue": "ingreso",
    "reversed": "revertido",
    "reverses": "revierte",
    "review": "revisión",
    "reviewed": "revisado",
    "role": "rol",
    "roster": "planilla",
    "round": "ronda",
    "rounds": "rondas",
    "rows": "filas",
    "run": "liquidación",
    "runs": "liquidaciones",
    "rut": "RUT",
    "sales": "ventas",
    "salon": "salón",
    "sample": "muestra",
    "schedule": "horario",
    "scope": "alcance",
    "sealed": "sellado",
    "seat": "silla",
    "seats": "sillas",
    "section": "sección",
    "sections": "secciones",
    "seen": "visto",
    "selections": "selecciones",
    "sent": "enviado",
    "seq": "secuencia",
    "series": "serie",
    "served": "servido",
    "session": "sesión",
    "settled": "liquidado",
    "settlement": "liquidación",
    "settlements": "liquidaciones",
    "share": "participación",
    "shared": "compartido",
    "shelf": "estante",
    "shift": "turno",
    "shifts": "turnos",
    "short": "corto",
    "shortage": "faltante",
    "side": "lado",
    "since": "desde",
    "skipped": "omitido",
    "sold": "vendido",
    "sort": "orden",
    "source": "origen",
    "spend": "gasto",
    "spent": "gastado",
    "split": "división",
    "splits": "divisiones",
    "staff": "personal",
    "stale": "desactualizado",
    "standard": "estándar",
    "star": "estrella",
    "start": "inicio",
    "station": "estación",
    "stations": "estaciones",
    "status": "estado",
    "still": "todavía",
    "stock": "existencia",
    "store": "sede",
    "stores": "sedes",
    "streak": "racha",
    "sub": "sub",
    "subscription": "suscripción",
    "substitute": "sustituto",
    "subtotal": "subtotal",
    "success": "éxito",
    "suggested": "sugerido",
    "suggestions": "sugerencias",
    "summary": "resumen",
    "sunday": "domingo",
    "superseded": "reemplazado",
    "supplier": "proveedor",
    "suppliers": "proveedores",
    "supply": "insumos",
    "surcharge": "recargo",
    "surplus": "sobrante",
    "sustained": "sostenido",
    "swap": "cambio",
    "swaps": "cambios",
    "table": "mesa",
    "tables": "mesas",
    "takeout": "para llevar",
    "target": "meta",
    "tax": "impuesto",
    "team": "equipo",
    "technical": "técnica",
    "tendered": "entregado",
    "term": "plazo",
    "text": "texto",
    "theoretical": "teórico",
    "this": "este",
    "threshold": "umbral",
    "ticket": "tiquete",
    "tickets": "tiquetes",
    "time": "tiempo",
    "tip": "propina",
    "tips": "propinas",
    "title": "título",
    "to": "hasta",
    "today": "hoy",
    "tolerance": "tolerancia",
    "tone": "tono",
    "total": "total",
    "totals": "totales",
    "transfer": "traslado",
    "transferred": "trasladado",
    "transfers": "traslados",
    "truncated": "truncado",
    "type": "tipo",
    "unallocated": "sin asignar",
    "unattributed": "sin atribuir",
    "unavailable": "agotado",
    "unclassified": "sin clasificar",
    "uncosted": "sin costo",
    "uncounted": "sin contar",
    "undeposited": "sin consignar",
    "unit": "unitario",
    "units": "unidades",
    "unknown": "desconocido",
    "unmatched": "sin cruzar",
    "unpaid": "sin cobrar",
    "unreliable": "no confiable",
    "unreviewed": "sin revisar",
    "unsent": "sin enviar",
    "until": "hasta",
    "untracked": "sin seguimiento",
    "unvalued": "sin valorar",
    "up": "arriba",
    "updated": "actualizado",
    "urgent": "urgente",
    "url": "URL",
    "usage": "uso",
    "use": "uso",
    "used": "usado",
    "user": "usuario",
    "uvt": "UVT",
    "valid": "vigente",
    "validated": "validado",
    "value": "valor",
    "variance": "varianza",
    "verify": "verificar",
    "version": "versión",
    "very": "muy",
    "via": "vía",
    "view": "vista",
    "views": "vistas",
    "void": "anulación",
    "voided": "anulado",
    "voids": "anulaciones",
    "wage": "salario",
    "waiter": "mesero",
    "waiters": "meseros",
    "waiting": "esperando",
    "walkouts": "fugas",
    "was": "era",
    "waste": "merma",
    "week": "semana",
    "weekday": "día de la semana",
    "weekly": "semanal",
    "window": "ventana",
    "windows": "ventanas",
    "with": "con",
    "withdrawn": "retirado",
    "without": "sin",
    "worked": "trabajado",
    "xml": "XML",
    "year": "año",
    "yellow": "amarillo",
    "yesterday": "ayer",
    "yield": "rendimiento",
    "zone": "zona",
    "zones": "zonas",
    # Palabras de las filas que arman los endpoints a mano (no vienen de un esquema).
    "x100": "(×100)",
    "micros": "(micros)",
    "has": "tiene",
    # Informe del contador, Hoy, nómina semanal y Cuadres (integración 2026-09-29).
    "adjustments": "ajustes",
    "all": "todas",
    "calendar": "calendario",
    "bar": "barra",
    "blocks": "bloques",
    "empty": "vacío",
    "concept": "concepto",
    "covered": "cubierto",
    "credit": "crédito",
    "cuadres": "cuadres",
    "desglose": "desglose",
    "editable": "editable",
    "offset": "desfase",
    "expense": "gasto",
    "goal": "meta",
    "inherited": "heredada",
    "met": "cumplida",
    "performance": "desempeño",
    "justification": "justificación",
    "segments": "tramos",
    "selected": "seleccionado",
    "shares": "participaciones",
    "consignable": "consignable",
    "top": "más vendidos",
    "shortfall": "faltante",
    "uncovered": "sin cubrir",
    "worst": "peor",
    # Etiquetas de cocina (0036).
    "copies": "copias",
    "left": "restantes",
    "names": "nombres",
    "height": "alto",
    "width": "ancho",
    "mm": "(mm)",
    "labels": "etiquetas",
    "made": "hecha",
    "openable": "para abrir",
    "outcome": "resultado",
    "state": "estado",
    "tomorrow": "mañana",
    "preview": "vista previa",
    "draft": "borrador",
    "recap": "repaso",
    # Gestión del período y estado de resultados (h2–h12).
    "affects": "afecta a",
    "authorizers": "autorizadores",
    "budget": "presupuesto",
    "budgetable": "presupuestable",
    "cells": "celdas",
    "controls": "controles",
    "goods": "de lo vendido",
    "month": "mes",
    "months": "meses",
    "labor": "mano de obra",
    "track": "en camino",
    "prime": "primo",
    "projected": "proyectado",
    "vs": "contra",
    "projection": "proyección",
    "reliability": "confiabilidad",
    "reliable": "confiable",
    "revpash": "RevPASH",
    "services": "servicios",
    "severity": "gravedad",
    "turnover": "rotación",
}

_RAW_KEY = re.compile(r"^[a-z0-9_]+$")

#: Palabras que en inglés van DESPUÉS del núcleo y en español se quedan al
#: final («con impuesto», «en pesos»): no se invierten.
_TRAILING = {"pct": "(%)", "bp": "(pb)", "x100": "(×100)", "micros": "(micros)", "mm": "(mm)"}


def untranslated_tokens(key: str) -> set[str]:
    """Las palabras de `key` que no tienen traducción (vacío = se traduce)."""
    if key in KEYS or not _RAW_KEY.match(key):
        return set()
    if "__" in key:
        out: set[str] = set()
        for part in key.split("__"):
            out |= untranslated_tokens(part)
        return out
    return {t for t in key.split("_") if t and t not in TOKENS}


def _capitalize(text: str) -> str:
    return text[:1].upper() + text[1:] if text else text


def spanish_header(key: str) -> str:
    """El encabezado en español de una clave de fila."""
    if key in KEYS:
        return KEYS[key]
    if not _RAW_KEY.match(key):
        return key  # ya viene escrito para personas (filas armadas a mano)
    if "__" in key:
        return " · ".join(spanish_header(part) for part in key.split("__") if part)
    tokens = [t for t in key.split("_") if t]
    suffix: list[str] = []
    while tokens and tokens[-1] in _TRAILING:
        suffix.insert(0, _TRAILING[tokens.pop()])
    when = False
    if tokens and tokens[-1] == "at" and len(tokens) > 1:
        tokens.pop()
        when = True
    is_question = bool(tokens) and tokens[0] in {"is", "has"} and len(tokens) > 1
    if is_question:
        tokens = tokens[1:]
    words = [TOKENS.get(t, t) for t in reversed(tokens)]
    text = " ".join(words)
    if when:
        text += " (fecha y hora)"
    if suffix:
        text += " " + " ".join(suffix)
    return _capitalize(text)
